// extract-openfoam-graph runs inside the OpenFOAM solver container, walks
// a decomposed case directory (processor0/, processor1/, ...) and emits an
// edge-list file that the topology-aware scheduler extender reads at
// placement time.
//
// Usage (inside MPIJob launcher init container):
//
//	cd /pvc/simulations/<jobID>
//	decomposePar -force
//	extract-openfoam-graph . > /scheduler-graphs/<jobID>.edgelist
//
// Output format (matches pkg/decomp.EdgeList):
//
//	# F-graph from OpenFOAM decomposition
//	N
//	I J Weight
//	...
package main

import (
	"fmt"
	"os"

	"github.com/theweirdfulmurk/cfd-platform/pkg/decomp"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: extract-openfoam-graph <case-dir>")
		os.Exit(2)
	}
	caseDir := os.Args[1]

	g, err := decomp.OpenFOAM(caseDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "extract:", err)
		os.Exit(1)
	}

	fmt.Println("# F-graph from OpenFOAM decomposition")
	fmt.Println("# generated by extract-openfoam-graph")
	fmt.Println(g.NumRanks)
	for _, e := range g.Edges {
		fmt.Printf("%d %d %g\n", e.I, e.J, e.Weight)
	}
}
