// extract-radioss-graph runs inside the OpenRadioss solver container,
// reads the METIS graph file written by the sed-patched Starter
// (IDB_METIS=1 in starter/source/spmd/domain_decomposition/grid2mat.F)
// together with the partition file produced by gpmetis, and emits an
// edge-list for the topology-aware scheduler extender.
//
// Usage (inside MPIJob launcher init container):
//
//	cd /pvc/simulations/<jobID>
//	starter_linux64_gf -np 16 -input *.rad         # writes input.graph0
//	gpmetis input.graph0 16                         # writes input.graph0.part.16
//	extract-radioss-graph input.graph0 input.graph0.part.16 \
//	    > /scheduler-graphs/<jobID>.edgelist
//
// Output format (matches pkg/decomp.EdgeList):
//
//	# F-graph from OpenRadioss + gpmetis partitioning
//	N
//	I J Weight
//	...
package main

import (
	"fmt"
	"os"

	"github.com/theweirdfulmurk/cfd-platform/pkg/decomp"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: extract-radioss-graph <input.graph0> <input.graph0.part.N>")
		os.Exit(2)
	}
	graphPath := os.Args[1]
	partPath := os.Args[2]

	g, err := decomp.METIS(graphPath, partPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "extract:", err)
		os.Exit(1)
	}

	fmt.Println("# F-graph from OpenRadioss METIS partitioning")
	fmt.Println("# generated by extract-radioss-graph")
	fmt.Println(g.NumRanks)
	for _, e := range g.Edges {
		fmt.Printf("%d %d %g\n", e.I, e.J, e.Weight)
	}
}
