#!/usr/bin/env python3
"""Build a communication graph F(i,j) for a Code_Aster mesh.

Workflow:

    1. Run `medpartitioner` (from the MEDCoupling toolkit, ships with Salome /
       code_aster) on the input .med mesh with --create-boundary-faces so that
       joints (shared-node info between subdomains) are persisted into the
       output MED files.
    2. Open each output `part_<i>.med` with the official MEDLoader Python API
       and walk `getJoints()`. Each joint references a neighbour subdomain
       and carries a correspondence list — its length is the number of nodes
       shared between domain i and the neighbour.
    3. Emit an edge-list file that `pkg/decomp.EdgeList()` reads natively:

           # NumRanks
           N
           # I J Weight
           0 1 124
           0 2 87
           ...

       Weight = number of shared nodes between domain i and j.

Why MEDLoader and not raw h5py? MEDLoader is the official EDF/CEA Python
binding to MEDCoupling, used by Code_Aster itself. It knows the exact MED
HDF5 layout, which has changed across MED minor versions. Using the API
guarantees correctness across med files written by different versions of
the partitioner.

Usage:

    extract_codeaster_graph.py --input mesh.med --ndomains 8 --output graph.edgelist
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    from MEDLoader import MEDFileMesh
except ImportError:  # pragma: no cover - hard dependency, fail loud
    sys.stderr.write(
        "error: MEDLoader (medcoupling) is required.\n"
        "Inside the Code_Aster container it is already on PYTHONPATH;\n"
        "outside, install via `conda install -c conda-forge medcoupling`\n"
    )
    sys.exit(2)


def run_medpartitioner(input_med: Path, ndomains: int, output_prefix: Path) -> None:
    """Invoke medpartitioner. Output goes next to output_prefix."""
    # medpartitioner accepts both `--flag=value` and `--flag value`; use the
    # space form which is supported on every version we've seen in the wild.
    cmd = [
        "medpartitioner",
        "--input-file", str(input_med),
        "--ndomains", str(ndomains),
        "--output-file", str(output_prefix),
        "--create-boundary-faces",
        "--plain-master",
    ]
    print(f"[extract] {' '.join(cmd)}", file=sys.stderr)
    subprocess.run(cmd, check=True)


def joint_weights(part_files: list[Path]) -> dict[tuple[int, int], int]:
    """Return {(i, j): shared_node_count} aggregated across part files.

    Verified against MEDFileJoint.hxx in SalomePlatform/medcoupling:

        MEDFileJoints   — getNumberOfJoints(), getJointAtPos(i)
        MEDFileJoint    — getDomainNumber(), getNumberOfSteps(), getStepAtPos(i)
        MEDFileJointOneStep
                        — getNumberOfCorrespondences(),
                          getCorrespondenceAtPos(i)
        MEDFileJointCorrespondence
                        — getIsNodal(), getCorrespondence() -> DataArrayIdType
        DataArrayIdType — getNumberOfTuples()

    A correspondence stores pairs (local_id, remote_id) — one row per shared
    entity. We take its tuple count when isNodal=True; cell correspondences
    are skipped because the scheduler models node-level exchanges, not
    overlapping element halos.
    """
    pairs: dict[tuple[int, int], int] = {}
    for i, path in enumerate(part_files):
        mesh = MEDFileMesh.New(str(path))
        joints = mesh.getJoints()
        if joints is None:
            continue
        for k in range(joints.getNumberOfJoints()):
            joint = joints.getJointAtPos(k)
            neighbour = int(joint.getDomainNumber())
            if neighbour == i:
                continue
            nb_shared_nodes = 0
            for step_idx in range(joint.getNumberOfSteps()):
                onestep = joint.getStepAtPos(step_idx)
                for c_idx in range(onestep.getNumberOfCorrespondences()):
                    corr = onestep.getCorrespondenceAtPos(c_idx)
                    if not corr.getIsNodal():
                        continue
                    arr = corr.getCorrespondence()
                    if arr is None:
                        continue
                    nb_shared_nodes += int(arr.getNumberOfTuples())
            if nb_shared_nodes == 0:
                continue
            pair = (min(i, neighbour), max(i, neighbour))
            pairs[pair] = pairs.get(pair, 0) + nb_shared_nodes
    # Each shared-node count appears on both sides of the joint; halve.
    return {p: w // 2 for p, w in pairs.items() if w > 0}


def write_edgelist(num_ranks: int, weights: dict[tuple[int, int], int], output: Path) -> None:
    with output.open("w") as f:
        f.write("# Generated by extract_codeaster_graph.py\n")
        f.write(f"{num_ranks}\n")
        for (i, j), w in sorted(weights.items()):
            f.write(f"{i} {j} {w}\n")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--input", required=True, type=Path, help="input MED mesh")
    ap.add_argument("--ndomains", required=True, type=int, help="number of MPI ranks")
    ap.add_argument("--output", required=True, type=Path, help="output edge-list path")
    ap.add_argument(
        "--workdir",
        type=Path,
        help="keep medpartitioner output here (default: temp dir, removed on exit)",
    )
    args = ap.parse_args()

    if not args.input.exists():
        ap.error(f"input not found: {args.input}")

    cleanup = args.workdir is None
    workdir = Path(tempfile.mkdtemp(prefix="medpart-")) if cleanup else args.workdir
    workdir.mkdir(parents=True, exist_ok=True)
    output_prefix = workdir / "part"

    try:
        run_medpartitioner(args.input, args.ndomains, output_prefix)
        part_files = sorted(workdir.glob("part_*.med"))
        if len(part_files) != args.ndomains:
            sys.stderr.write(
                f"warning: medpartitioner produced {len(part_files)} files, "
                f"expected {args.ndomains}\n"
            )
        weights = joint_weights(part_files)
        write_edgelist(args.ndomains, weights, args.output)
        print(
            f"[extract] wrote {len(weights)} edges across {args.ndomains} ranks "
            f"to {args.output}",
            file=sys.stderr,
        )
    finally:
        if cleanup:
            import shutil

            shutil.rmtree(workdir, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
